name: Publish LangFlow Backend & Frontend to GHCR

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  push-langflow-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ---- Build & Push Backend Image ----
      - name: Build LangFlow Backend Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_NAME/langflow:latest -f ./docker/build_and_push.Dockerfile .
          docker push ghcr.io/$REPO_NAME/langflow:latest

      # ---- Build & Push Frontend Image ----
      - name: Build LangFlow Frontend Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_NAME/langflow-frontend:latest -f ./docker/frontend/build_and_push_frontend.Dockerfile .
          docker push ghcr.io/$REPO_NAME/langflow-frontend:latest